apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: pod-dive
spec:
  version: "v0.1.5"
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/caiobegotti/pod-dive/releases/download/v0.1.5/pod-dive-amd64-linux.tar.gz
    sha256: "6ba0fb94abda46018a1409f7517868e135be44bbfa1ab76ebd0ce244954748f5"
    files:
    - from: "./LICENSE"
      to: "."
    - from: "./pod-dive-amd64-linux"
      to: "."
    bin: "pod-dive-amd64-linux"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/caiobegotti/pod-dive/releases/download/v0.1.5/pod-dive-amd64-darwin.tar.gz
    sha256: "cf0f3e6b630e334a366759e3549977f6c540650aaf7a22af376f41d3e345b564"
    files:
    - from: "./LICENSE"
      to: "."
    - from: "./pod-dive-amd64-darwin"
      to: "."
    bin: "pod-dive-amd64-darwin"
  - selector:
      matchLabels:
        os: darwin
        arch: arm64
    uri: https://github.com/caiobegotti/pod-dive/releases/download/v0.1.5/pod-dive-arm64-darwin.tar.gz
    sha256: "e2ce0619e56acd353358910a76586b3eb7864775ce16966077d7a06edcea9f49"
    files:
    - from: "./LICENSE"
      to: "."
    - from: "./pod-dive-arm64-darwin"
      to: "."
    bin: "pod-dive-arm64-darwin"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/caiobegotti/pod-dive/releases/download/v0.1.5/pod-dive-amd64-windows.exe.zip
    sha256: "00d0a7f65b27e5d253d1f7be46730917583dc20ff27bd13c39e875f2e37e13b0"
    files:
    - from: "./LICENSE"
      to: "."
    - from: "./pod-dive-amd64-windows.exe"
      to: "."
    bin: "pod-dive-amd64-windows.exe"
  shortDescription: Shows a pod's workload tree and info inside a node
  homepage: https://github.com/caiobegotti/pod-dive
  description: |
    Dives into a node after the desired pod and returns data associated
    with the pod no matter where it is running, such as its origin workload,
    namespace, the node where it is running and its node pod siblings, as
    well basic health status of it all.

    The purpose is to have meaningful pod info at a glance without needing to
    run multiple kubectl commands to see what else is running next to your
    pod in a given node inside a huge cluster, because sometimes all
    you've got from an alert is the pod name.

    Usage
      $ kubectl pod-dive [pod name]

    For additional options
      $ kubectl pod-dive --help
